namespace PropertyAccessorGenerator;

using System;
using System.Diagnostics;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

/// <summary>
/// Generates source that adds TryGetValue(string, out object?) extension accessors for types marked with
/// Annotations.PropertyAccessorAttribute{T}.
/// </summary>
/// <remarks>
/// Implemented as an IIncrementalGenerator. It finds class or struct declarations annotated with
/// Annotations.PropertyAccessorAttribute`1, extracts the attribute type argument, enumerates the target type's public
/// properties, and emits a partial static type containing an extension TryGetValue method that returns a property value
/// by name. Generated files are named {TypeName}.g.cs, include nullable annotations, and use the declaring type's
/// accessibility and kind (class or struct). Only public properties are exposed.
/// </remarks>
[Generator]
public class PropertyAccessorGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var markedTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
            "Annotations.PropertyAccessorAttribute`1",
            predicate: static (node, _) => node is ClassDeclarationSyntax || node is StructDeclarationSyntax,
            transform: static (ctx, _) =>
            {
#if DEBUG
                if (!Debugger.IsAttached)
                {
                    ////Debugger.Launch();
                }
#endif

                INamedTypeSymbol accessorSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
                AttributeData? attrData = ctx.Attributes.FirstOrDefault();
                if (attrData == null)
                {
                    return null;
                }

                // Extract type parameter from attribute
                ITypeSymbol? targetSymbol = attrData.AttributeClass?.TypeArguments.FirstOrDefault();
                if (targetSymbol == null)
                {
                    return null;
                }

                string typeArg = targetSymbol.Name;
                if (string.IsNullOrWhiteSpace(typeArg))
                {
                    return null;
                }

                string accessorNamespace = accessorSymbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : accessorSymbol.ContainingNamespace.ToDisplayString();
                string targetNamespace = targetSymbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : targetSymbol.ContainingNamespace.ToDisplayString();

                IPropertySymbol[] properties = targetSymbol
                    .GetMembers()
                    .OfType<IPropertySymbol>()
                    .Where(p => p.DeclaredAccessibility == Accessibility.Public)
                    .ToArray();

                return new ClassInfo()
                {
                    Name = accessorSymbol.Name,
                    AccessorNamespace = accessorNamespace,
                    TargetNamespace = targetNamespace,
                    TargetType = typeArg,
                    AccessModifier = accessorSymbol.DeclaredAccessibility.ToString().ToLowerInvariant(),
                    TargetProperties = properties,
                };
            })
            .Where(static info => info is not null);

        // Generate Python code for each marked class
        context.RegisterSourceOutput(markedTypes, static (spc, info) =>
        {
            string code = GeneratePartialAccessorSource(info!);
            spc.AddSource($"{info!.Name}.g.cs", code);
        });
    }

    /// <summary>
    /// Generates source code for a partial accessor type that provides a name-based TryGetValue accessor for instances
    /// of the target type described by the provided ClassInfo.
    /// </summary>
    /// <remarks>The generated source includes an auto-generated header, nullable enable/restore directives,
    /// necessary using directives, an optional namespace declaration, and a static partial type containing an
    /// extension-style TryGetValue(string, out object?) method that switches on property names and returns values or
    /// null using MaybeNullWhen annotations.</remarks>
    /// <param name="info">ClassInfo describing the target type, including namespace, access modifier, type identifier, and properties to
    /// include in the generated accessor.</param>
    /// <returns>The generated C# source code for the partial accessor as a string.</returns>
    private static string GeneratePartialAccessorSource(ClassInfo info)
    {
        StringBuilder sb = new();
        sb.AppendLine($"// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.AccessorNamespace))
        {
            sb.AppendLine($"namespace {info.AccessorNamespace};");
            sb.AppendLine();
        }

        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Immutable;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");

        if (!string.IsNullOrEmpty(info.TargetNamespace))
        {
            sb.AppendLine($"using {info.TargetNamespace};");
        }
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Provides a name-based accessor for retrieving property values from a {info.TargetType} instance.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"{info.AccessModifier} static partial class {info.Name}");
        sb.AppendLine("{");
        sb.AppendLine($"    extension({info.TargetType} item)");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Gets the values for the specified property names from the underlying item.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <remarks>Values may be null. If propertyNames contains duplicates, the last occurrence");
        sb.AppendLine("        /// determines the stored value. The method uses TryGetPropertyValue to determine presence of each");
        sb.AppendLine("        /// property.</remarks>");
        sb.AppendLine("        /// <param name=\"names\">An array of property names to retrieve; only names present on the item are included in the result.</param>");
        sb.AppendLine("        /// <returns>A read-only dictionary mapping each found property name to its value. Names not present on the item are");
        sb.AppendLine("        /// omitted; returns an empty dictionary if no names are provided or none are found.</returns>");
        sb.AppendLine("        /// <exception cref=\"ArgumentNullException\">Thrown when <paramref name=\"names\"/> is null.</exception>");
        sb.AppendLine("        /// <exception cref=\"ArgumentException\">Thrown when a property name is null, empty, or consists only of white-space characters.</exception>");
        sb.AppendLine($"        {info.AccessModifier} IReadOnlyDictionary<string, object?> GetPropertyValues(string[] names)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(names);");
        sb.AppendLine();
        sb.AppendLine("            if (names.Length == 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                return ImmutableDictionary<string, object?>.Empty;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            Dictionary<string, object?> results = new();");
        sb.AppendLine("            foreach (string name in names)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (item.TryGetPropertyValue(name, out object? value))");
        sb.AppendLine("                {");
        sb.AppendLine("                    results[name] = value;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return results;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Attempts to get the value associated with the specified key.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"name\">The name of the property to retrieve.</param>");
        sb.AppendLine("        /// <param name=\"value\">When the method returns, contains the value associated with the specified key if found; otherwise, <see langword=\"null\"/>.</param>");
        sb.AppendLine("        /// <returns>true if the key was found; otherwise, false.</returns>");
        sb.AppendLine("        /// <exception cref=\"ArgumentException\">Thrown when <paramref name=\"name\"/> is null, empty, or consists only of white-space characters.</exception>");
        sb.AppendLine($"        {info.AccessModifier} bool TryGetPropertyValue(string name, [MaybeNullWhen(false)] out object? value)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentException.ThrowIfNullOrWhiteSpace(name);");
        sb.AppendLine();
        sb.AppendLine("            switch (name)");
        sb.AppendLine("            {");

        foreach (var p in info.TargetProperties)
        {
            var name = p.Name;
            sb.AppendLine($"                case \"{name}\":");
            sb.AppendLine($"                    value = item.{name};");
            sb.AppendLine("                    return true;");
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    value = default;");
        sb.AppendLine("                    return false;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        sb.AppendLine();
        sb.AppendLine("#nullable restore");

        return sb.ToString();
    }

    private class ClassInfo
    {
        public string Name { get; set; } = string.Empty;

        public string AccessorNamespace { get; set; } = string.Empty;

        public string TargetNamespace { get; set; } = string.Empty;

        public string AccessModifier { get; set; } = "private";

        public string TargetType { get; set; } = string.Empty;

        public IPropertySymbol[] TargetProperties { get; set; } = Array.Empty<IPropertySymbol>();
    }
}
